# Generated by Django 4.2.7 on 2023-12-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='avaliable_quantity',
            field=models.FloatField(),
        ),
    ]
