# Generated by Django 4.2.7 on 2023-12-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_avaliable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
