# Generated by Django 4.2.7 on 2023-12-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_reciperequirement_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='avaliable_quantity',
            new_name='available_quantity',
        ),
    ]
