# Generated by Django 4.2.7 on 2023-12-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_avaliable_quantity_ingredient_available_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='available_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='menuitem',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='menuitem',
            new_name='menu_item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
