# Generated by Django 4.2.7 on 2023-12-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_available_quantity_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
