# Generated by Django 4.2.7 on 2023-12-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
